// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAZJLjagH6_aMyUAR2DrbffeELulKdxUY',
    appId: '1:690916075724:web:dfa59dbd0af97a1e5c3a69',
    messagingSenderId: '690916075724',
    projectId: 'a-ya-a552f',
    authDomain: 'a-ya-a552f.firebaseapp.com',
    storageBucket: 'a-ya-a552f.appspot.com',
    measurementId: 'G-54W1F3ZJ7X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfMEKLVNDgs8V60Xyawe_3klyH-KrOIs0',
    appId: '1:690916075724:android:a5e0becce23b19f75c3a69',
    messagingSenderId: '690916075724',
    projectId: 'a-ya-a552f',
    storageBucket: 'a-ya-a552f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4p9BZPCf_TFTk_TcPHRRp2Xsq9i9WL9o',
    appId: '1:690916075724:ios:a592702febe4b5eb5c3a69',
    messagingSenderId: '690916075724',
    projectId: 'a-ya-a552f',
    storageBucket: 'a-ya-a552f.appspot.com',
    iosClientId: '690916075724-ger9kt5cbrrrj5dk23sakd8huchoaif0.apps.googleusercontent.com',
    iosBundleId: 'com.aya.aya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4p9BZPCf_TFTk_TcPHRRp2Xsq9i9WL9o',
    appId: '1:690916075724:ios:a592702febe4b5eb5c3a69',
    messagingSenderId: '690916075724',
    projectId: 'a-ya-a552f',
    storageBucket: 'a-ya-a552f.appspot.com',
    iosClientId: '690916075724-ger9kt5cbrrrj5dk23sakd8huchoaif0.apps.googleusercontent.com',
    iosBundleId: 'com.aya.aya',
  );
}
